spring.application.name=catalogo
server.port=8082

# Permite inyectar la URL desde Docker o usa localhost por defecto si pruebas en tu PC
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/petly?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
